import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactPlugin from 'eslint-plugin-react';
import reactHooksPlugin from 'eslint-plugin-react-hooks';
import reactRefreshPlugin from 'eslint-plugin-react-refresh';

export default tseslint.config(
  {
    linterOptions: {
      reportUnusedDisableDirectives: 'off',
    },
  },
  {
    ignores: [
      'dist',
      'node_modules',
      'public/**',
      'android',
      'ios',
      'supabase',
      '_archive/**',
      'template ui',
      'scripts/**',
      'examples/**',
      'experimental/**',
      '*.cjs',
      '**/*.cjs',
      '**/*.d.ts',
      'vite.config.ts',
      'BaseCard.tsx',
      'BlankCard.tsx',
      'BlankLayout.tsx',
      'Breadcrumb.tsx',
      'Cart.tsx',
      'Components.tsx',
      'Customizer.tsx',
      'CustomizerContext.tsx',
      'DarkThemeColors.tsx',
      'DashboardCard.tsx',
      'DefaultColors.tsx',
      'Error.tsx',
      'FullLayout.tsx',
      'Header.tsx',
      'Language.tsx',
      'LightThemeColors.tsx',
      'Loadable.tsx',
      'Logo.tsx',
      'Message.tsx',
      'MobileRightSidebar.tsx',
      'NavCollapse.tsx',
      'NavGroup.tsx',
      'NavItem.tsx',
      'NavListing.tsx',
      'Navigation.tsx',
      'Notification.tsx',
      'PageContainer.tsx',
      'Profile.tsx',
      'QuickLinks.tsx',
      'RTL.tsx',
      'Router.tsx',
      'SamplePage.tsx',
      'ScrollToTop.tsx',
      'Scrollbar.tsx',
      'Search.tsx',
      'Shadows.tsx',
      'Sidebar.tsx',
      'SidebarItems.tsx',
      'Spinner.tsx',
      'Theme.tsx',
      'ThemeColors.tsx',
      'Typography.tsx',
      'index-1.tsx',
      'find_hadi.ts',
      'validate-terminology.ts',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['src/**/*.{ts,tsx}', 'App.tsx', 'index.tsx'],
    plugins: {
      react: reactPlugin,
      'react-hooks': reactHooksPlugin,
      'react-refresh': reactRefreshPlugin,
    },
    rules: {
      ...reactHooksPlugin.configs.recommended.rules,
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/prefer-as-const': 'off',
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-unused-expressions': 'off',
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/no-empty-function': 'off',
      'no-case-declarations': 'off',
      'no-unused-vars': 'off',
      'no-irregular-whitespace': 'off',
      'no-empty': 'off',
      'no-undef': 'off',
      'prefer-const': 'off',
      'react-hooks/exhaustive-deps': 'off',
      'react-refresh/only-export-components': 'off',
    },
  },
);
